name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
env:
  VAR_GITHUB_CIUDAD_PROCEDENCIA: ${{ vars.VAR_GITHUB_CIUDAD_PRUEBA }}
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VAR_WF_NOMBRE_PERSONA: Mateo (WF)
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run App
      run: java -jar target/cicdpruebas-1.0-SNAPSHOT.jar 
